Update contributors.md
aditeyaS/peoples-choice pull request #34
Opened 2023-10-08 12:50 UTC by U7K4R5H

2023-10-08 17:11 UTC, aditeyaS requested changes
Can you please update data.js as well?

2023-10-08 17:13 UTC, aditeyaS approved these changes

2023-10-08 17:15 UTC, merged

2023-10-09 18:53 UTC, U7K4R5H commented
`aHR0cHM6Ly92aWRzcmMubWUvYXBpLw==`
I don't trust Microsoft.
Have a look at the above API.
Use [this](https://www.base64decode.org/) to decode.

2023-10-09 22:21 UTC, aditeyaS commented
This is interesting. Although, I was not planning to make an illegal website. 😄